const mongoose = require('mongoose');
const timeSheetSchema = new mongoose.Schema({
    aiid: {type:String},
    piid:{type: String},
    personAssigned:{type:String},
    addedWithFutureDates:{type:String},
    adminOfficeAccounts:{type:String},
    job1:{type:String},
    workDesc1:{type:String},
    job1MaintenanceLog:{type:String},
    job1Breakdownlog:{type:String},
    job1Repairlog:{type:String},
    job1InvestigationLog: {type:String},
    job1TimeSpent:{type:String},
    job1WorkDesc:{type:String},
    job1DistanceFrom:{type:String},
    job1DistanceTo:{type:String},
    job1Kms:{type:String},
    job2:{type:String},
    job2MaintenanceLog:{type:String},
    job2Breakdownlog:{type:String},
    job2Repairlog:{type:String},
    job2InvestigationLog: {type:String},
    job2TimeSpent:{type:String},
    job2WorkDesc:{type:String},
    job2DistanceFrom:{type:String},
    job2DistanceTo:{type:String},
    job2Kms:{type:String},
    job3:{type:String},
    job3MaintenanceLog:{type:String},
    job3Breakdownlog:{type:String},
    job3Repairlog:{type:String},
    job3InvestigationLog: {type:String},
    job3TimeSpent:{type:String},
    job3WorkDesc:{type:String},
    job3DistanceFrom:{type:String},
    job3DistanceTo:{type:String},
    job3Kms:{type:String},
    job4:{type:String},
    job4MaintenanceLog:{type:String},
    job4Breakdownlog:{type:String},
    job4Repairlog:{type:String},
    job4InvestigationLog: {type:String},
    job4TimeSpent:{type:String},
    job4WorkDesc:{type:String},
    job4DistanceFrom:{type:String},
    job4DistanceTo:{type:String},
    job4Kms:{type:String},
    job5:{type:String},
    job5MaintenanceLog:{type:String},
    job5Breakdownlog:{type:String},
    job5Repairlog:{type:String},
    job5InvestigationLog: {type:String},
    job5TimeSpent:{type:String},
    job5WorkDesc:{type:String},
    job5DistanceFrom:{type:String},
    job5DistanceTo:{type:String},
    job5Kms:{type:String},
    typeOfLeave:{type:String},
    leave:{type:String},
    leaveCategory:{type:String},
    leaveDetails:{type:String},
    totalKms:{type:String},
    totalTimeSpent:{type:String},
    ordinaryHours:{type:String},
    timeAndHalf:{type:String},
    doubleTime:{type:String},
    rdoHours:{type:String},
    leaveFileLink:{type:String},
    createdOn: {type : Date},
})

module.exports = mongoose.model('TimeSheet', timeSheetSchema);